package com.example.cs2340c_team22.models.drawable;

public class RoomLayouts {
    public static final int ROOM_COL_TILES = 12;
    public static final int ROOM_ROW_TILES = 15;
    public static final int NUM_ROOMS = 3;

    public static final TileType[][][] ROOM_LAYOUTS = {
        {
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.EXIT_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
        },
        {
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.EXIT_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
        },
        {
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FLOOR_TILE,
                TileType.FLOOR_TILE, TileType.FLOOR_TILE, TileType.FINAL_EXIT_TILE,
                TileType.WALL_TILE},
            {TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE,
                TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, TileType.WALL_TILE, },
        }
    };
}
